export type Technology = "Solar" | "Wind" | "Hybrid";
export type SECType = "Fixed" | "Variable";
export type StackReplacementType =
  | "Cumulative Hours"
  | "Maximum Degradation Level";

export type ChartData = { label: string; data: number[] };

export interface InputFields {
  additionalUpfrontCosts: number;
  additionalAnnualCosts: number;
  batteryEpcCosts?: number;
  batteryEfficiency: number;
  batteryMinCharge?: number;
  batteryLandProcurementCost?: number;
  batteryRatedPower?: number;
  batteryCosts?: number;
  batteryOMCost?: number;
  batteryReplacementCost?: number;
  batteryLifetime?: number;
  discountRate: number;
  durationOfStorage: number;
  electrolyserCostReductionWithScale: number;
  electrolyserEpcCosts: number;
  electrolyserLandProcurementCost: number;
  electrolyserReferenceFoldIncrease: number;
  electrolyserOMCost: number;
  electrolyserStackReplacement: number;
  gridConnectionCost: number;
  batteryNominalCapacity?: number;
  electrolyserNominalCapacity: number;
  solarNominalCapacity: number;
  windNominalCapacity: number;
  solarReferenceCapacity: number;
  windReferenceCapacity: number;
  electrolyserReferenceCapacity: number;
  electrolyserReferencePurchaseCost: number;
  solarPVFarmReferenceCost: number;
  windFarmReferenceCost: number;
  solarEpcCosts: number;
  solarLandProcurementCost: number;
  solarPVCostReductionWithScale: number;
  solarReferenceFoldIncrease: number;
  solarOpex?: number;
  stackReplacementType: StackReplacementType;
  stackLifetime: number;
  stackDegradation: number;
  maximumDegradationBeforeReplacement: number;
  technology: Technology;
  totalNominalPowerPlantCapacity: number;
  electrolyserWaterCost: number;
  windCostReductionWithScale: number;
  windEpcCosts: number;
  windLandProcurementCost: number;
  windReferenceFoldIncrease: number;
  windOpex?: number;
  plantLife: number;
  additionalTransmissionCharges?: number;
  principalPPACost?: number;
  profile: SECType;
  region: string;
  electrolyserMaximumLoad: number;
  electrolyserMinimumLoad: number;
  timeBetweenOverloading: number;
  maximumLoadWhenOverloading: number;
  waterRequirementOfElectrolyser: number;
  h2RetailPrice: number;
  oxygenRetailPrice: number;
  averageElectricitySpotPrice: number;
  shareOfTotalInvestmentFinancedViaEquity: number;
  directEquityShare: number;
  salvageCostShare: number;
  decommissioningCostShare: number;
  loanTerm: number;
  interestOnLoan: number;
  capitalDepreciaitonProfile: string;
  taxRate: number;
  inflationRate: number;
}
