name: Test and Deploy
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.py"
      - "**.csv"
      - "**.txt"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.py"
      - "**.csv"
      - "**.txt"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
          cache: npm
      - run: npm install
      - run: npm test
      - run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 0364a3323bfef6416e3a4da5c07d5e97
          projectName: nswp2xtool
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
